//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::blacklisted_feature_author::Entity as BlacklistedFeatureAuthor;
pub use super::featured_level::Entity as FeaturedLevel;
pub use super::queued_level::Entity as QueuedLevel;
pub use super::sent_level::Entity as SentLevel;
