//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "queued_level")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub priority: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub author: i64,
    #[sea_orm(column_type = "Text")]
    pub author_name: String,
    pub rate_tier: i64,
    pub feature_duration: Option<i64>,
    pub queued_at: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
