//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "sent_level")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub level_id: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub author: i64,
    #[sea_orm(column_type = "Text")]
    pub author_name: String,
    pub rate_tier: i64,
    pub sent_by: i64,
    #[sea_orm(column_type = "Text")]
    pub note: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
