//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub account_id: i64,
    pub cube: i64,
    pub color1: i64,
    pub color2: i64,
    pub glow_color: i64,
    pub username: Option<String>,
    pub name_color: Option<String>,
    pub is_whitelisted: bool,
    pub admin_password_hash: Option<String>,
    pub roles: Option<String>,
    pub active_mute: Option<i64>,
    pub active_ban: Option<i64>,
    pub active_room_ban: Option<i64>,
    pub discord_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
