//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub account_id: i32,
    pub username: Option<String>,
    pub name_color: Option<String>,
    pub is_whitelisted: bool,
    pub admin_password_hash: Option<String>,
    pub roles: Option<String>,
    pub active_mute: Option<i32>,
    pub active_ban: Option<i32>,
    pub active_room_ban: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
